#
# Autogenerated by Avro
#
#DO NOT EDIT DIRECTLY
#
from avro.schema import parse

class Position:
    _schema = parse('''{\"type\":\"enum\",\"name\":\"Position\",\"namespace\":\"avro.examples.baseball\",\"symbols\":[\"P\",\"C\",\"B1\",\"B2\",\"B3\",\"SS\",\"LF\",\"CF\",\"RF\",\"DH\"]}''')
    P = 'P'
    C = 'C'
    B1 = 'B1'
    B2 = 'B2'
    B3 = 'B3'
    SS = 'SS'
    LF = 'LF'
    CF = 'CF'
    RF = 'RF'
    DH = 'DH'
